# Generated by Django 3.0.4 on 2020-03-15 11:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200314_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='detail',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='picture',
            field=models.ImageField(blank=True, upload_to=api.models.uploadLocation),
        ),
    ]
