# Generated by Django 3.0.4 on 2020-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200321_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
