# Generated by Django 3.0.4 on 2020-03-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200321_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='status',
            field=models.BooleanField(),
        ),
    ]
