# Generated by Django 3.0.4 on 2020-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200321_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('B', 'Cho bán'), ('S', 'Cho thuê')], max_length=30),
        ),
    ]
