# Generated by Django 3.0.4 on 2020-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200321_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('B', 'Mua'), ('S', 'Bán')], max_length=30),
        ),
    ]
