# Generated by Django 3.0.4 on 2020-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200321_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('Mua', 'Mua'), ('Bán', 'Bán')], max_length=30),
        ),
    ]
