# Generated by Django 3.0.4 on 2020-03-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200321_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='transaction',
        ),
        migrations.AddField(
            model_name='post',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TransactionType'),
        ),
    ]
