# Generated by Django 3.0.4 on 2020-03-22 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200321_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.Province'),
        ),
    ]
