# Generated by Django 3.0.4 on 2020-03-29 09:29

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200322_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=api.models.uploadLocation)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Estate')),
            ],
        ),
    ]
