# Generated by Django 3.0.4 on 2020-03-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_estateimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='picture',
        ),
    ]
