# Generated by Django 3.0.4 on 2020-04-02 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_estate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='created_day',
            field=models.DateTimeField(default=datetime.date(2020, 4, 2)),
        ),
    ]
