# Generated by Django 3.0.4 on 2020-04-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_filtertype_sorttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.District'),
        ),
        migrations.AddField(
            model_name='project',
            name='lat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lng',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='province_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Province'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
