# Generated by Django 3.0.4 on 2020-04-11 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200411_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.District'),
        ),
        migrations.AlterField(
            model_name='project',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Province'),
        ),
    ]
