# Generated by Django 3.0.4 on 2020-04-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200411_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtertype',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sorttype',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
