# Generated by Django 3.0.4 on 2020-04-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200411_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtertype',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sorttype',
            name='value',
            field=models.IntegerField(),
        ),
    ]
