# Generated by Django 3.0.4 on 2020-04-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_filterarea_filterminprice_filternumberofroom_filterposttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='api.Project'),
        ),
    ]
