# Generated by Django 3.0.4 on 2020-04-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200417_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
