# Generated by Django 3.0.4 on 2020-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200414_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='addressDetail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
