# Generated by Django 3.0.4 on 2020-04-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200422_0446'),
        ('api', '0030_auto_20200417_0715'),
    ]

    operations = [
    ]
