# Generated by Django 3.0.4 on 2020-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200510_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estate',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
