# Generated by Django 3.0.4 on 2020-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200510_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='lat2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='lng2',
            field=models.FloatField(default=0),
        ),
    ]
