# Generated by Django 3.0.4 on 2020-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200510_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
