# Generated by Django 3.0.4 on 2020-05-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200511_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=30)),
                ('price', models.BigIntegerField(blank=True, default=0, null=True)),
                ('area', models.FloatField(blank=True, default=0.0, null=True)),
                ('timestamp', models.DateTimeField()),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('estateType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.EstateType')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Province')),
            ],
        ),
    ]
