# Generated by Django 3.0.4 on 2020-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
