# Generated by Django 3.0.4 on 2020-05-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200512_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='transaction',
        ),
        migrations.AddField(
            model_name='estate',
            name='transaction',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TransactionType'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(choices=[('Thuê', 'Thuê'), ('Bán', 'Bán')], max_length=30),
        ),
    ]
