# Generated by Django 3.0.4 on 2020-05-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200512_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Tracking'},
        ),
    ]
