# Generated by Django 3.0.4 on 2020-05-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200517_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={},
        ),
    ]
