# Generated by Django 3.0.4 on 2020-07-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_isagency'),
        ('api', '0055_auto_20200703_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('timestamp', models.DateTimeField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User')),
            ],
        ),
    ]
