# Generated by Django 3.0.4 on 2020-07-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_isagency'),
        ('api', '0056_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=100)),
                ('estateId', models.CharField(max_length=100)),
                ('ratingType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RatingType')),
            ],
        ),
    ]
