# Generated by Django 3.0.4 on 2020-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20200730_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
