# Generated by Django 3.0.4 on 2020-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_estate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
