# Generated by Django 3.0.4 on 2020-08-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_isagency'),
        ('api', '0059_auto_20200730_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_type',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.District')),
                ('estateType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EstateType')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
