# Generated by Django 3.0.4 on 2020-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('emailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('identifyNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
