# Generated by Django 3.0.4 on 2020-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200414_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAgency',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
