USER_EXIST = 'username is existed'
EMAIL_EXIST = 'email is registered'
ERROR_CODE = 'error_code'
ERROR_MESSAGE = 'error_message'
CONTENT_TYPE_JSON = 'application/json'
REQUEST = 'request'
TYPE = 'type'
ID = 'id'

EC_SUCCESS = '0'
EC_FAIL = '100'
EC_USERNAME_EXIST = '1'
EC_EMAIL_EXIST = '2'
EC_IMAGE_LARGE = '3'
EC_IMAGE_RATIO = '4'

EM_SUCCESS = 'Success.'
EM_FAIL = 'Something went wrong - '
EM_USERNAME_EXIST = 'Username existed.'
EM_EMAIL_EXIST = 'Email existed.'
EM_IMAGE_LARGE = 'That image is too large. Images must be less than 2 MB. Try a different image.'
EM_IMAGE_RATIO = 'Image height must not exceed image width. Try a different image.'
